# Original author: zerodds
# Source: https://github.com/starship/starship/discussions/1107#discussioncomment-11750241
# Adaptations: see ../CREDITS.md
"$schema" = "https://starship.rs/config-schema.json"
"add_newline" = false
"format" = "[╭](#ffffff) [](#ffffff)[ $os ](fg:#3a9efd bg:#ffffff)[ ](#ffffff)$username$directory$all$line_break$character"
"right_format" = "$git_branch$git_state$git_status$time"
["os"]
"format" = "$symbol"
"disabled" = false
["os"."symbols"]
"Alpine" = ""
"Amazon" = ""
"Android" = ""
"Arch" = "󰣇"
"CentOS" = ""
"Debian" = ""
"EndeavourOS" = ""
"Fedora" = ""
"FreeBSD" = ""
"Garuda" = ""
"Gentoo" = ""
"Linux" = ""
"Macos" = ""
"Manjaro" = ""
"Mariner" = ""
"Mint" = ""
"NetBSD" = ""
"NixOS" = ""
"OpenBSD" = ""
"OpenCloudOS" = ""
"openEuler" = ""
"openSUSE" = ""
"OracleLinux" = "⊂⊃"
"Pop" = ""
"Raspbian" = ""
"Redhat" = ""
"RedHatEnterprise" = ""
"Solus" = ""
"SUSE" = ""
"Ubuntu" = ""
"Unknown" = ""
"Windows" = ""
["character"]
"success_symbol" = "[╰─❯](#ffffff)"
"error_symbol" = "[╰─×](#ff0000)"
["git_branch"]
"format" = "[ $symbol $branch ]($style) "
"symbol" = ""
"style" = "#00ff00"
["directory"]
"format" = "[](#3a9efd)[$path]($style)[ ](#3a9efd)"
"style" = "fg:#ffffff bg:#3a9efd"
"truncate_to_repo" = false
["username"]
"style_user" = "#3a9efd"
"show_always" = true
"disabled" = true
["time"]
"format" = "[$time](#ffff00)"
"time_format" = "%a, %I:%M %p"
"disabled" = false
["hostname"]
"disabled" = true
["localip"]
"disabled" = true
["aws"]
"disabled" = true
["gcloud"]
"disabled" = true
["azure"]
"disabled" = true
["kubernetes"]
"disabled" = true
["docker_context"]
"disabled" = true
["env_var"]
"disabled" = true
["sudo"]
"disabled" = true
