"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory\
$git_branch\
$git_status\
$nodejs\
$bun\
$rust\
$golang\
$php\
\n$character"""

[directory]
style = "fg:#b8b4a8"
format = "[ $path ]($style)"
truncation_length = 0
truncate_to_repo = false
home_symbol = "~"


[git_branch]
symbol = ""
style = "fg:#8ea99a"
format = '[[ $symbol $branch ](fg:#8ea99a)]($style)'

[git_status]
style = "fg:#8ea99a"
format = '[[($all_status$ahead_behind )](fg:#8ea99a)]($style)'

[nodejs]
symbol = ""
style = "fg:#a89d8c"
format = '[[ $symbol ($version) ](fg:#a89d8c)]($style)'

[bun]
symbol = ""
style = "fg:#a89d8c"
format = '[[ $symbol ($version) ](fg:#a89d8c)]($style)'

[rust]
symbol = ""
style = "fg:#a89d8c"
format = '[[ $symbol ($version) ](fg:#a89d8c)]($style)'

[golang]
symbol = ""
style = "fg:#a89d8c"
format = '[[ $symbol ($version) ](fg:#a89d8c)]($style)'

[php]
symbol = ""
style = "fg:#a89d8c"
format = '[[ $symbol ($version) ](fg:#a89d8c)]($style)'

[time]
disabled = true

[character]
success_symbol = "[❯](fg:#8ea99a)"
error_symbol = "[❯](fg:#c78179)"
