# Cool slate; custom restrained ANSI palette.
font-family = JetBrainsMono Nerd Font Mono
font-size = 14
background = #22272e
foreground = #c5cbd2
background-opacity = 1
background-blur = 0
selection-background = #3c4652
selection-foreground = #dde3e9
cursor-color = #b4c0cb
cursor-text = #22272e
split-divider-color = #3c4652
adjust-cell-height = 8%
window-padding-x = 12
window-padding-y = 10
palette = 0=#22272e
palette = 1=#c98585
palette = 2=#a3b58b
palette = 3=#c5af83
palette = 4=#8faec3
palette = 5=#b6a0be
palette = 6=#88b4ad
palette = 7=#c5cbd2
palette = 8=#7a8591
palette = 9=#c98585
palette = 10=#a3b58b
palette = 11=#c5af83
palette = 12=#8faec3
palette = 13=#b6a0be
palette = 14=#88b4ad
palette = 15=#dde3e9
