# mist reading preset
font-family = JetBrainsMono Nerd Font Mono
font-size = 14
background = #e4ebe5
foreground = #3f4d43
background-opacity = 1
background-blur = 0
selection-background = #c4cdd3
selection-foreground = #303b45
cursor-color = #526675
cursor-text = #e4ebe5
split-divider-color = #bac4cc
adjust-cell-height = 8%
window-padding-x = 12
window-padding-y = 10
palette = 0=#3f4d43
palette = 1=#a44343
palette = 2=#4c6849
palette = 3=#806020
palette = 4=#38647a
palette = 5=#79557e
palette = 6=#376d68
palette = 7=#c9c3b7
palette = 8=#737067
palette = 9=#ab4646
palette = 10=#426343
palette = 11=#896420
palette = 12=#365f7c
palette = 13=#76547c
palette = 14=#326863
palette = 15=#ded9ce
