"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory\
$git_branch\
$git_status\
$nodejs\
$bun\
$rust\
$golang\
$php\
\n$character"""

[directory]
style = "fg:#beb0c3"
format = "[ $path ]($style)"
truncation_length = 0
truncate_to_repo = false
home_symbol = "~"


[git_branch]
symbol = ""
style = "fg:#b1a0bc"
format = '[[ $symbol $branch ](fg:#b1a0bc)]($style)'

[git_status]
style = "fg:#b1a0bc"
format = '[[($all_status$ahead_behind )](fg:#b1a0bc)]($style)'

[nodejs]
symbol = ""
style = "fg:#b8aaa0"
format = '[[ $symbol ($version) ](fg:#b8aaa0)]($style)'

[bun]
symbol = ""
style = "fg:#b8aaa0"
format = '[[ $symbol ($version) ](fg:#b8aaa0)]($style)'

[rust]
symbol = ""
style = "fg:#b8aaa0"
format = '[[ $symbol ($version) ](fg:#b8aaa0)]($style)'

[golang]
symbol = ""
style = "fg:#b8aaa0"
format = '[[ $symbol ($version) ](fg:#b8aaa0)]($style)'

[php]
symbol = ""
style = "fg:#b8aaa0"
format = '[[ $symbol ($version) ](fg:#b8aaa0)]($style)'

[time]
disabled = true

[character]
success_symbol = "[❯](fg:#b1a0bc)"
error_symbol = "[❯](fg:#cf9294)"
